name: better_video_trimmer
description: An updated version of better_video_trimmer using betterPlayer for a better compatibility.
version: 3.0.1
homepage: https://github.com/AdrienGaill/better_video_trimmer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  better_player: ^0.0.84
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  path_provider: ^2.1.1
  intl: ^0.20.2
  path: ^1.8.3
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.1

flutter:
